baseURL = "https://drycola.com/"  # 改成你的实际 URL 或 GitHub Pages 地址
languageCode = "zh-cn"
title = "Drycola"
theme = "PaperMod"
enableRobotsTXT = true  # 生成 robots.txt 文件

# 输出格式配置（用于搜索功能）
[outputs]
  home = ["HTML", "RSS", "JSON"]

# 网站元信息配置
[params]
  author = "王小铁"
  description = "Daily life in Japan"
  keywords = ["Blog", "Japan", "Travel", "Daily"]
  
  # PaperMod 主题配置
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

  # Profile模式配置
  [params.profileMode]
    enabled = true
    title = "王小铁"
    subtitle = "在这里我会分享我在日本的日常生活，和我所关心的政治议题。"
    
    [[params.profileMode.buttons]]
      name = "文章"
      url = "/posts/"
    
    [[params.profileMode.buttons]]
      name = "归档"
      url = "/archive/"
    
    [[params.profileMode.buttons]]
      name = "标签"
      url = "/tags/"

  # 网站图标配置
  [params.assets]
    favicon = "/favicon.ico"
    favicon16x16 = "/favicon-16x16.svg"
    favicon32x32 = "/favicon.svg"

# 主菜单配置
[[menu.main]]
name = "归档"
url = "/archive/"
weight = 10

[[menu.main]]
name = "搜索"
url = "/search/"
weight = 20

[[menu.main]]
name = "标签"
url = "/tags/"
weight = 30

[[menu.main]]
name = "分类"
url = "/categories/"
weight = 40


# 语言配置
[languages]
  [languages.zh-cn]
    title = "Drycola"
    weight = 1
    languageName = "zh-cn"
    description = "Daily life in Japan"

  [languages.en]
    title = "Drycola"
    weight = 2
    languageName = "English"
    description = "Daily life in Japan"
