baseURL = "https://datiewang.github.io/"  # 改成你的实际 URL 或 GitHub Pages 地址
languageCode = "zh-cn"
title = "Drycola"
theme = "PaperMod"
enableRobotsTXT = true  # 生成 robots.txt 文件

# 网站元信息配置
[params]
  author = "王小铁"
  description = "Daily life in Japan"
  keywords = ["Blog", "Japan", "Travel", "Daily"]

# 本地开发服务器配置
[server]
  port = 1313
  baseURL = "http://localhost:1313"

# 语言配置
[languages]
  [languages.zh-cn]
    title = "Drycola"
    weight = 1
    languageName = "zh-cn"
    description = "Daily life in Japan"

  [languages.en]
    title = "Drycola"
    weight = 2
    languageName = "English"
    description = "Daily life in Japan"
