baseURL = "https://drycola.com/"  # 改成你的实际 URL 或 GitHub Pages 地址
languageCode = "en"
title = "Drycola"
theme = "PaperMod"
enableRobotsTXT = true  # 生成 robots.txt 文件

# 输出格式配置（用于搜索功能）
[outputs]
  home = ["HTML", "RSS", "JSON"]

# 网站元信息配置
[params]
  author = "datiewang"
  description = "Chronicling life in Japan. Politics, culture, and the spaces between."
  keywords = ["Blog", "Japan", "Politics", "Culture", "Daily Life"]
  
  # PaperMod 主题配置
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

  # Home Info 模式配置 (Regular Mode)
  [params.homeInfoParams]
    Title = "datiewang"
    Content = "Chronicling life in Japan. Politics, culture, and the spaces between."
  
  # 社交图标配置（可选）
  socialIcons = [
    {name = "github", url = "https://github.com/datiewang"}
  ]

  # 网站图标配置
  [params.assets]
    favicon = "/favicon.ico"
    favicon16x16 = "/favicon-16x16.svg"
    favicon32x32 = "/favicon.svg"

# 主菜单配置
[[menu.main]]
name = "Archive"
url = "/archive/"
weight = 10

[[menu.main]]
name = "Categories"
url = "/categories/"
weight = 20

[[menu.main]]
name = "Search"
url = "/search/"
weight = 30

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 40
